import type { Metadata } from "next";
import StyledComponentsRegistry from './lib/registry';
import { Comfortaa } from "next/font/google";
import { ModalProvider } from "./contexts/ModalContexts";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <ModalProvider>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </ModalProvider>
      </body>
    </html>
  );
}
