"use client"

import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import styled from "styled-components";
import { Poppins } from "next/font/google";


//-- FONTE
const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin']})

//-- BODY
const Body = styled.body`
  display: flex;
  flex-direction: column;
  width: auto;
  height: max-content;
  align-items: center;
  font-size: 1rem;

  background: linear-gradient(
    to bottom,
    hsla(31, 69%, 35%, 0.8) 10%,
    hsl(31, 69%, 35%) 23.5rem,
    hsl(44, 61%, 74%) 23.5rem,
    hsl(44, 61%, 74%)
  ) hsl(0, 0%, 100%);
  @media (min-width: 768px) {
    background: linear-gradient(
      hsla(31, 69%, 35%, 0.8) 10%,
      hsl(31, 69%, 35%) 23.5rem,
      hsl(44, 61%, 74%) 23.5rem,
      hsl(44, 61%, 74%)
    ) hsl(0, 0%, 100%);
  } 
`

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



//-- ROOT
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Body className={poppins.className}>

        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>

      </Body>
    </html>
  );
}
