"use client"

import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import styled from "styled-components";
import { Poppins } from "next/font/google";
import clsx from "clsx";

//-- FONT
const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin']})

//-- BODY
const Body = styled.body`
  display: flex;
  flex-direction: column;
  align-items: center;
  align-content: center;
  width: auto;
  height: 100vh;
  margin: 0;
  padding: 0;
`

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//-- ROOT
export default function RootLayout({
    children,
    className
  }: IProps) {
  return (
    <html lang="pt-br">
      <Body className={ clsx(poppins.className, className) }>

        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>

      </Body>
    </html>
  );
}